[repository]
name = "hyprexpo-dong"
authors = ["dong"]


[hyprexpo-dong]
description = "A plugin to add expo (overlay) for workspaces"
authors = ["dong"]
output = "hyprexpo/hyprexpo.so"
build = [
    "make -C hyprexpo all",
]
since_hyprland = 4364