[repository]
name = "hyprexpo-dong"
authors = ["dong"]


[hyprexpo]
description = "A plugin to add expo (overlay) for workspaces"
authors = ["Vaxry"]
output = "hyprexpo.so"
build = [
    "make all",
]
since_hyprland = 4364